server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CANDIDATE-APP
          uri: lb://CANDIDATE-APP
          predicates:
            - Path=/candidate/**
        - id: JOB-APP
          uri: lb://JOB-APP
          predicates:
            - Path=/jobs/**

eureka:
  client:
    register-with-eureka: true

  service-url: http://localhost:8761/eureka


